/** Public paths for asset logos (mirrors frontend AssetLogo image map). */
const SYMBOL_LOGOS: Record<string, string> = {
  TSLA: '/symbols/tsla.webp',
  NVDA: '/symbols/nvidia.webp',
  AAPL: '/symbols/apple.webp',
  GOOGL: '/symbols/google.webp',
  GOOG: '/symbols/google.webp',
  AMZN: '/symbols/amazon.webp',
  MSFT: '/symbols/microsoft.webp',
  META: '/symbols/meta.webp',
  INTC: '/symbols/intel.webp',
  AMD: '/symbols/amd.webp',
  COIN: '/symbols/coinbase.webp',
  HOOD: '/symbols/hood.webp',
  MSTR: '/symbols/mstr.webp',
  BOT: '/symbols/bot.webp',
  PURRDAT: '/symbols/purr.webp',
  PLTR: '/symbols/pltr.webp',
  CRCL: '/symbols/crcl.webp',
  CRWV: '/symbols/crwv.webp',
  SPCX: '/symbols/spcx.webp',
  CXMT: '/symbols/cxmt.webp',
  UNITREE: '/symbols/unitree.webp',
  MRNA: '/symbols/mrna.webp',
  CBRS: '/symbols/cbrs.webp',
  IBM: '/symbols/ibm.webp',
  DELL: '/symbols/dell.webp',
  AVGO: '/symbols/avgo.webp',
  MRVL: '/symbols/mrvl.webp',
  COST: '/symbols/cost.webp',
  NFLX: '/symbols/nflx.webp',
  TSM: '/symbols/tsm.webp',
  RIVN: '/symbols/rivn.webp',
  MU: '/symbols/micron.webp',
  GME: '/symbols/gme.webp',
  LLY: '/symbols/lly.webp',
  BABA: '/symbols/baba.webp',
  SNDK: '/symbols/sndk.webp',
  ORCL: '/symbols/oracle.webp',
  SKHY: '/symbols/skhy.webp',
  SMSN: '/symbols/samsung.webp',
  LITE: '/symbols/lite.webp',
  NDX100: '/symbols/ndx100.webp',
  SP500: '/symbols/sp500.webp',
  EWY: '/symbols/ewy.webp',
  DRAM: '/symbols/dram.webp',
  GOLD: '/symbols/gold.webp',
  SILVER: '/symbols/silver.webp',
  PLATINUM: '/symbols/platinum.webp',
  PALLADIUM: '/symbols/palladium.webp',
  COPPER: '/symbols/copper.webp',
  OIL: '/symbols/oil.webp',
  CL: '/symbols/oil.webp',
  BZ: '/symbols/oil.webp',
  BRENTOIL: '/symbols/oil.webp',
  NATGAS: '/symbols/natgas.webp',
  URNM: '/symbols/uranium.webp',
  EUR: '/symbols/eur.webp',
  JPY: '/symbols/jpy.webp',
  BTC: '/symbols/btc-icon.webp',
  ETH: '/symbols/eth-icon.webp',
  SOL: '/symbols/sol-icon.webp',
  XRP: '/symbols/xrp-icon.webp',
  ZEC: '/symbols/zcash-icon.webp',
  HYPE: '/symbols/hype-icon.webp',
  LIT: '/symbols/lit-icon.webp',
  BNB: '/symbols/bnb-icon.webp',
  LINK: '/symbols/link-icon.webp',
  AAVE: '/symbols/aave-icon.webp',
  KNTQ: '/symbols/kntq-icon.webp',
  XPL: '/symbols/xpl-icon.webp',
  SUI: '/symbols/sui-icon.webp',
  XMR: '/symbols/xmr-icon.webp',
  UNI: '/symbols/uni-icon.webp',
  ONDO: '/symbols/ondo-icon.webp',
  GRAM: '/symbols/ton-icon.webp',
  TRX: '/symbols/trx-icon.webp',
  ADA: '/symbols/ada-icon.webp',
  AVAX: '/symbols/avax-icon.webp',
  ENA: '/symbols/ena-icon.webp',
  MON: '/symbols/mon-icon.webp',
  WLD: '/symbols/wld-icon.webp',
  ZRO: '/symbols/zro-icon.webp',
  APT: '/symbols/apt-icon.webp',
  WLFI: '/symbols/wlfi-icon.webp',
  TAO: '/symbols/tao-icon.webp',
  BCH: '/symbols/bch-icon.webp',
  XLM: '/symbols/xlm-icon.webp',
  HBAR: '/symbols/hbar-icon.webp',
  LTC: '/symbols/ltc-icon.webp',
  JUP: '/symbols/jup-icon.webp',
  JTO: '/symbols/jto-icon.webp',
  PYTH: '/symbols/pyth-icon.webp',
  NEAR: '/symbols/near-icon.webp',
  ARB: '/symbols/arb-icon.webp',
  VVV: '/symbols/vvv-icon.webp',
  MEGA: '/symbols/mega-icon.webp',
  VIRTUAL: '/symbols/virtual-icon.webp',
  PONS: '/symbols/pons-icon.webp',
  ASTER: '/symbols/aster-icon.webp',
  USDT: '/symbols/usdt-icon.webp',
};

export function symbolLogoKey(symbol: string): string {
  const raw = (symbol || '').trim().toUpperCase();
  if (!raw) return '';
  const i = raw.indexOf(':');
  return i >= 0 ? raw.slice(i + 1) : raw;
}

export function symbolLogoSrc(symbol: string): string | null {
  const key = symbolLogoKey(symbol);
  return SYMBOL_LOGOS[key] ?? null;
}
